MIST:
  species: 'Human' #either Mouse or Human
  n_pcs: 5 # number of PCs to be used
  min_sim: 0.5 # minimum of similarity scores for thresholding
  max_sim: 0.91 # maximum of similarity scores for thresholding
  min_cell_count: 3
  min_read_count: 200
  min_region_size: 20 # minimum region size
  hvg_prop: 0.9 #top 90% of hvgs used
  step_size: 0.02 #search step of the weights

RESORT:
  Cancer: ['TM4SF1']
  Ductal: ['CRISP3']
  Other Normal: ['PRSS1']

CellHierarchy: 
  Cancer: ['Cancer']
  Ductal: ['Ductal - APOL1 high', 'Ductal - CRISP3 high', 'Ductal - MHC Class II', 'Ductal - terminal ductal like']
  Other Normal: ['Acinar cells', 'Endocrine cells', 'Endothelial cells', 'Macrophages', 'Mast cells', 'Monocytes', 'T cells & NK cells', 'Tuft cells', 'mDCs', 'pDCs']